
@files = %w[vimrc zshrc gemrc gitconfig tmux.conf]
@dotfiles_dir = File.expand_path(__dir__)
# bin/tmux/* is linked into ~/bin/tmux/, matching the $HOME/bin/tmux/ paths
# used by tmux.conf and the theme files.
@tmux_bin_files = %w[
  tmux-circle-number.sh
  tmux-mode-pill.sh
  tmux-popup-menu.sh
  tmux-right-status.py
  tmux-session-style.sh
  tmux-workstate.py
]
# bin/misc/* is linked flat into ~/bin because ~/bin is on PATH and these are
# commands typed by hand.
@misc_bin_files = %w[ws]
@tmux_theme_files = %w[
  tokyonight.conf
  monokai.conf
  github-light.conf
]

task :install do
  @files.each do |file_name|
    print "linking #{file_name}\n"
    print `ln -sfn #{@dotfiles_dir}/#{file_name} ~/.#{file_name}`
    print "\n"
  end
end

task :tmux do
  print "linking tmux.conf\n"
  print `ln -sfn #{@dotfiles_dir}/tmux.conf ~/.tmux.conf`

  print "ensuring ~/.tmux/themes exists\n"
  print `mkdir -p ~/.tmux/themes`

  @tmux_theme_files.each do |file_name|
    print "linking theme #{file_name}\n"
    print `ln -sfn #{@dotfiles_dir}/tmux/themes/#{file_name} ~/.tmux/themes/#{file_name}`
    print "\n"
  end

  print "ensuring ~/bin/tmux exists\n"
  print `mkdir -p ~/bin/tmux`

  @tmux_bin_files.each do |file_name|
    print "linking #{file_name}\n"
    print `chmod +x #{@dotfiles_dir}/bin/tmux/#{file_name}`
    print `ln -sfn #{@dotfiles_dir}/bin/tmux/#{file_name} ~/bin/tmux/#{file_name}`
    print "\n"
  end
end

task :misc do
  print "ensuring ~/bin exists\n"
  print `mkdir -p ~/bin`

  @misc_bin_files.each do |file_name|
    print "linking #{file_name}\n"
    print `chmod +x #{@dotfiles_dir}/bin/misc/#{file_name}`
    print `ln -sfn #{@dotfiles_dir}/bin/misc/#{file_name} ~/bin/#{file_name}`
    print "\n"
  end
end

# Only the files actually customized are tracked here. Everything else in
# ~/.config/nvim (init.lua, lua/config/lazy.lua, LICENSE, stylua.toml, ...) is
# byte-identical to the upstream LazyVim starter, so the task clones the starter
# on a fresh machine and links these files over the top of it.
#
# lazy-lock.json is deliberately NOT linked: it is regenerated by lazy.nvim on
# every plugin update and would churn this repo on every :Lazy update.
@nvim_files = %w[
  lazyvim.json
  lua/config/autocmds.lua
  lua/config/keymaps.lua
  lua/config/options.lua
  lua/plugins/colorscheme.lua
  lua/plugins/command-palette.lua
  lua/plugins/disable-bufferline.lua
  lua/plugins/disable-linting.lua
  lua/plugins/fzf.lua
  lua/plugins/lualine.lua
  lua/plugins/ruby-lsp.lua
  lua/plugins/vimwiki.lua
  lua/plugins/zen.lua
]
@lazyvim_starter = "https://github.com/LazyVim/starter.git"

task :nvim do
  dest = File.expand_path("~/.config/nvim")

  if File.symlink?(dest)
    abort "~/.config/nvim is a symlink; remove it and re-run so the starter can be cloned"
  end

  unless File.directory?(dest)
    print "cloning LazyVim starter into ~/.config/nvim\n"
    print `git clone --depth 1 #{@lazyvim_starter} #{dest}`
    # The starter's own git history is not wanted; this repo is the source of truth.
    print `rm -rf #{dest}/.git`
  end

  @nvim_files.each do |file_name|
    src = "#{@dotfiles_dir}/nvim/#{file_name}"
    target = "#{dest}/#{file_name}"

    print "linking nvim/#{file_name}\n"
    print `mkdir -p #{File.dirname(target)}`
    print `ln -sfn #{src} #{target}`
    print "\n"
  end
end

task :herdr do
  print "ensuring ~/.config/herdr exists\n"
  print `mkdir -p ~/.config/herdr`

  print "linking herdr/config.toml\n"
  print `ln -sfn #{@dotfiles_dir}/herdr/config.toml ~/.config/herdr/config.toml`
  print "\n"
end

task :uninstall do
  @files.each do |file_name|
    `rm ~/.#{file_name}`
  end
end
