set -g window-style "bg=default"
set -g window-active-style "bg=colour236"
set -g status-style "bg=#1f2335,fg=#a9b1d6"
set -g message-style "bg=default"
set -g message-command-style "bg=default"

run-shell "/bin/bash /Users/wusher/mine/dot_files/bin/tmux-session-style.sh #{session_name}"
run-shell "/bin/bash /Users/wusher/mine/dot_files/bin/tmux-session-style.sh ghub"
run-shell "/bin/bash /Users/wusher/mine/dot_files/bin/tmux-session-style.sh scrach"
run-shell "/bin/bash /Users/wusher/mine/dot_files/bin/tmux-session-style.sh scratch"
set-hook -g client-session-changed 'run-shell "/bin/bash /Users/wusher/mine/dot_files/bin/tmux-session-style.sh #{session_name}"'
set-hook -g session-created 'run-shell "/bin/bash /Users/wusher/mine/dot_files/bin/tmux-session-style.sh #{hook_session_name}"'
set-hook -g session-renamed 'run-shell "/bin/bash /Users/wusher/mine/dot_files/bin/tmux-session-style.sh #{hook_session_name}"'

set -g pane-border-style "fg=colour240,bg=default"
set -g pane-active-border-style "fg=colour45,bg=default"
unbind -T prefix z
